# Generated by Django 3.2.9 on 2021-11-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('product_img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
