# Generated by Django 3.2.9 on 2021-12-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211201_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='username',
        ),
    ]
